Moved auth-tokens-* and clients-* back to Bash formulations

diff --git a/bin/clients-list b/bin/clients-list
--- a/bin/clients-list
+++ b/bin/clients-list
@@ -1,52 +1,150 @@
-#!/usr/bin/env python
-"""
-clients-list [flags] [client name]
+#!/bin/bash
+#
+# clients-list
+#
+# author: opensource@tacc.cloud
+#
+# This script is part of the Agave API command line interface (CLI).
+# It retrieves a list of one or more registered clients.
+#
 
-Lists all Tapis Oauth clients registered to the user on a tenant.
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-Flags:
-    -u, --username      Username.
-    -p, --password      Password.
-    -t, --tenant        Tenant id where clients are registered.
-    -c, --cachedir      Session cache directory.
-"""
-from __future__ import print_function
-import argparse
-import sys
-from agavepy.agave import Agave
-from agavepy import utils
+source "$DIR/common.sh"
+interactive=1
 
-parser = argparse.ArgumentParser(
-    description="Lists all Tapis Oauth clients registered to the user on a tenant.")
+# Script logic -- TOUCH THIS {{{
 
-parser.add_argument("-u", "--username", default=None, help="Username.")
-parser.add_argument("-p", "--password", default=None, help="Password.")
-parser.add_argument("-t", "--tenant", default=None,
-                    help="Tenant id where clients are registered.")
+# A list of all variables to prompt in interactive mode. These variables HAVE
+# to be named exactly as the longname option definition in usage().
+interactive_opts=(apiusername apipassword)
 
-parser.add_argument(
-    "-c",
-    "--cachedir",
-    default=utils.credentials_cache_dir(),
-    help="Session cache directory.")
+# Print usage
+usage() {
+  echo -n "$(basename $0) [OPTION]...
+$(basename $0) [OPTION]... [CLIENT_NAME]
 
-if __name__ == "__main__":
-    args = parser.parse_args()
+List all API clients registered to the authenticated user.
 
-    username = args.username
-    password = args.password
-    tenantid = args.tenant
-    cache_dir = args.cachedir
-    agave = Agave()
+ Options:
+  -u, --apiusername    API apiusername
+  -p, --apipassword    API apipassword
+  -l, --limit          Maximum number of results to return
+  -o, --offset         Number of results to skip from the start
+  -H, --hosturl        URL of the service
+  -d, --development    Run in dev mode using default dev server
+  -f, --force          Skip all user interaction
+  -i, --interactive    Prompt for values
+  -q, --quiet          Quiet (no output)
+  -v, --verbose        Verbose output
+  -V, --veryverbose    Very verbose output
+  -h, --help           Display this help and exit
+      --version        Output version information and exit
+      --rich           Provide rich response
+"
+}
 
-    context = utils.bootstrap_context(
-        cache_dir, tenantid=tenantid, username=username)
-    agave = Agave(tenant_id=context['tenantid'], username=context['username'])
-    agave.init()
+##################################################################
+##################################################################
+#						Begin Script Logic						 #
+##################################################################
+##################################################################
 
-    # List clients.
-    try:
-        agave.clients_list(password=password, quiet=False)
-    except Exception as err:
-        print(err)
-        sys.exit(1)
+source "$DIR/clients-common.sh"
+
+main() {
+	#echo -n
+	#set -x
+
+	if [ -n "$args" ]; then
+		clientsurl="${hosturl}${args}?pretty=true$(pagination)"
+	else
+		clientsurl="${hosturl}?pretty=true$(pagination)"
+	fi
+
+	cmd="curl -sku \"${apiusername}:xxxx\" '${clientsurl}'"
+
+	if ((veryverbose)); then
+		[ "$piped" -eq 0 ] && log "Calling $cmd"
+	fi
+
+	response=`curl -sku "${apiusername}:${apipassword}" "${clientsurl}"`
+
+	if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+		result=$(format_api_json "$response")
+		success "$result"
+	else
+		errorresponse=$(jsonquery "$response" "message")
+		err "$errorresponse"
+	fi
+}
+
+format_api_json() {
+
+	if ((veryverbose)); then
+		json_prettyify "${1}"
+	elif [[ $verbose -eq 1 ]]; then
+		result=$(jsonquery "$1" "result" 1)
+		json_prettyify "${result}"
+	elif [[ $rich -eq 1 ]]; then
+		result=$(richify "$1")
+		columnize "${result}"
+	elif [ -n "$args" ]; then
+		result=$(jsonquery "$1" "result.name")
+		echo "${result}"
+	else
+		result=$(jsonquery "$1" "result.[].name")
+		echo "${result}"
+	fi
+}
+
+##################################################################
+##################################################################
+#						End Script Logic						 #
+##################################################################
+##################################################################
+
+# }}}
+
+# Parse command line options
+source "$DIR/options.sh"
+
+
+# Main loop {{{
+
+# Print help if no arguments were passed.
+#[[ $# -eq 0 ]] && set -- "--help"
+
+# Read the options and set stuff
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; safe_exit ;;
+    --version) version; copyright; disclaimer; safe_exit ;;
+    -u|--apiusername) shift; apiusername=$1 ;;
+    -p|--apipassword) shift; apipassword=$1;;
+    -l|--limit) shift; limit=$1;;
+    -o|--offset) shift; offset=$1;;
+  	--order) shift; sortOrder=$1;;
+  	--orderBy) shift; sortBy=$1;;
+    --filter) shift; responsefilter=$1 ;;
+    -H|--hosturl) shift; hosturl=$1;;
+  	-d|--development) development=1 ;;
+    -v|--verbose) verbose=1 ;;
+    -V|--veryverbose) veryverbose=1; verbose=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -i|--interactive) interactive=1 ;;
+    -f|--force) force=1 ;;
+    --rich) rich=1 ;;
+    --endopts) shift; break ;;
+    *) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+# Store the remaining part as arguments.
+args+=("$@")
+
+# }}}
+
+# Run the script logic
+source "$DIR/runner.sh"
diff --git a/bin/clients-subscriptions-list b/bin/clients-subscriptions-list
--- a/bin/clients-subscriptions-list
+++ b/bin/clients-subscriptions-list
@@ -1,57 +1,143 @@
-#!/usr/bin/env python
-"""
-    Usage: clients-subscriptions-list [OPTIONS]
+#!/bin/bash
+#
+# clients-subscriptions-list
+#
+# author: opensource@tacc.cloud
+#
+# This script is part of the Agave API command line interface (CLI).
+# It retrieves a list of API subscriptions for the named client
+#
 
-Lists API subscriptions for a Tapis Oauth client
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-Flags:
-    -N, --name          Client name.
-    -u, --username      Username.
-    -p, --password      Password.
-    -t, --tenant        Tenant id where client is registered.
-    -c, --cachedir      Session cache directory.
-"""
-from __future__ import print_function
-import argparse
-import sys
-from agavepy.agave import Agave
-from agavepy import utils
+source "$DIR/common.sh"
+interactive=1
 
-parser = argparse.ArgumentParser(
-    description="Lists API subscriptions for a Tapis Oauth client.")
+# Script logic -- TOUCH THIS {{{
 
-parser.add_argument("-N", "--name", help="Name of Oauth client.")
-parser.add_argument("-u", "--username", default=None, help="Username.")
-parser.add_argument("-p", "--password", default=None, help="Password.")
-parser.add_argument("-t", "--tenant", default=None,
-                    help="Tenant id where client is registered.")
-parser.add_argument(
-    "-c",
-    "--cachedir",
-    default=utils.credentials_cache_dir(),
-    help="Session cache directory.")
+# A list of all variables to prompt in interactive mode. These variables HAVE
+# to be named exactly as the longname option definition in usage().
+interactive_opts=(apiusername apipassword)
 
-if __name__ == "__main__":
-    args = parser.parse_args()
+# Print usage
+usage() {
+  echo -n "$(basename $0) [OPTION]... [CLIENT_NAME]
 
-    cache_dir = args.cachedir
-    username = args.username
-    password = args.password
-    tenantid = args.tenant
-    clientname = args.name
+List all APIs to which the client is subscribed.
 
-    agave = Agave()
+ Options:
+  -u, --apiusername    API apiusername
+  -p, --apipassword    API apipassword
+  -l, --limit          Maximum number of results to return
+  -o, --offset         Number of results to skip from the start
+  -H, --hosturl        URL of the service
+  -d, --development    Run in dev mode using default dev server
+  -f, --force          Skip all user interaction
+  -i, --interactive    Prompt for values
+  -q, --quiet          Quiet (no output)
+  -v, --verbose        Verbose output
+  -V, --veryverbose    Very verbose output
+  -h, --help           Display this help and exit
+      --version        Output version information and exit
+      --rich           Provide rich response
+"
+}
 
-    context = utils.bootstrap_context(
-        cache_dir, tenantid=tenantid, username=username)
-    agave = Agave(tenant_id=context['tenantid'], username=context['username'])
-    agave.init()
+##################################################################
+##################################################################
+#						Begin Script Logic						 #
+##################################################################
+##################################################################
 
-    # List client's subscriptions.
-    try:
-        agave.clients_subscriptions(
-            client_name=clientname,
-            password=password, quiet=False)
-    except Exception as err:
-        print(err)
-        sys.exit(1)
+source "$DIR/clients-common.sh"
+
+main() {
+	#echo -n
+	#set -x
+
+	if [ -z "$args" ]; then
+		err "Please specify a valid client for which to list subscriptions"
+	else
+		cmd="curl -sku \"${apiusername}:${apipassword}\" '${hosturl}${args}/subscriptions?pretty=true$(pagination)'"
+
+		if ((veryverbose)); then
+			[ "$piped" -eq 0 ] && log "Calling $cmd"
+		fi
+
+		response=`curl -sku "${apiusername}:${apipassword}" "${hosturl}${args}/subscriptions?pretty=true$(pagination)"`
+
+		if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+			result=$(format_api_json "$response")
+			success "$result"
+		else
+			errorresponse=$(jsonquery "$response" "message")
+			err "$errorresponse"
+		fi
+
+	fi
+}
+
+format_api_json() {
+
+	if ((veryverbose)); then
+		json_prettyify "${1}"
+	elif [[ $verbose -eq 1 ]]; then
+		result=$(jsonquery "$1" "result" 1)
+		json_prettyify "${result}"
+	elif [[ $rich -eq 1 ]]; then
+		result=$(richify "$1")
+		columnize "${result}"
+	else
+		result=$(jsonquery "$1" "result.[].apiName")
+		echo "${result}"
+	fi
+}
+
+##################################################################
+##################################################################
+#						End Script Logic						 #
+##################################################################
+##################################################################
+
+# }}}
+
+# Parse command line options
+source "$DIR/options.sh"
+
+
+# Main loop {{{
+
+# Print help if no arguments were passed.
+#[[ $# -eq 0 ]] && set -- "--help"
+
+# Read the options and set stuff
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; safe_exit ;;
+    --version) version; copyright; disclaimer; safe_exit ;;
+    -u|--apiusername) shift; apiusername=$1 ;;
+    -p|--apipassword) shift; apipassword=$1 ;;
+    -l|--limit) shift; limit=$1;;
+    -o|--offset) shift; offset=$1;;
+    --filter) shift; responsefilter=$1 ;;
+    -H|--hosturl) shift; hosturl=$1;;
+  	-d|--development) development=1 ;;
+    -v|--verbose) verbose=1 ;;
+    -V|--veryverbose) veryverbose=1; verbose=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -i|--interactive) interactive=1 ;;
+    -f|--force) force=1 ;;
+    --rich) rich=1 ;;
+    --endopts) shift; break ;;
+    *) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+# Store the remaining part as arguments.
+args+=("$@")
+
+# }}}
+
+# Run the script logic
+source "$DIR/runner.sh"
diff --git a/bin/clients-subscriptions-update b/bin/clients-subscriptions-update
--- a/bin/clients-subscriptions-update
+++ b/bin/clients-subscriptions-update
@@ -1,78 +1,150 @@
-#!/usr/bin/env python
-"""
-    Usage: clients-subscriptions-update [OPTIONS] [CLIENT NAME]
+#!/bin/bash
+#
+# clients-subscriptions-update
+#
+# author: opensource@tacc.cloud
+#
+# This script is part of the Agave API command line interface (CLI).
+# It subscribes the client to one or all APIs.
+#
 
-Update or add API subscriptions for a Tapis Oauth client.
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-Flags:
-    -N, --name          Client name.
-    -a, --apiname       Name of the API to subscribe the client application to
-    -r, --apiversion    Version of the API to subscribe the client application to
-    -P, --apiprovider   User who registered the API
-    -u, --username      Username.
-    -p, --password      Password.
-    -t, --tenant        Tenant id where client is registered.
-    -c, --cachedir      Session cache directory.
-    -h, --help          Display this help and exit
-"""
-from __future__ import print_function
-import argparse
-import os
-import sys
-from agavepy.agave import Agave
-from agavepy import utils
+source "$DIR/common.sh"
+interactive=1
 
-parser = argparse.ArgumentParser(
-    description="Updates or adds API subscriptions for a Tapis Oauth client.")
+# Script logic -- TOUCH THIS {{{
 
-parser.add_argument("-N", "--name", help="Name of Oauth client.")
-parser.add_argument(
-    "-a",
-    "--apiname",
-    required=True,
-    help="Name of the API to subscribe the client to.")
-parser.add_argument(
-    "-r",
-    "--apiversion",
-    required=True,
-    help="Version of the API to subscribe the client to.")
-parser.add_argument(
-    "-P", "--apiprovider", required=True, help="User who registered the API.")
+# A list of all variables to prompt in interactive mode. These variables HAVE
+# to be named exactly as the longname option definition in usage().
+interactive_opts=(apiusername apipassword apiName)
 
-parser.add_argument("-u", "--username", default=None, help="Username.")
-parser.add_argument("-p", "--password", default=None, help="Password.")
-parser.add_argument("-t", "--tenant", default=None,
-                    help="Tenant id where client is registered.")
+# Print usage
+usage() {
+  echo -n "$(basename $0) [OPTION]... [CLIENT_NAME]
 
-parser.add_argument(
-    "-c",
-    "--cachedir",
-    default=utils.credentials_cache_dir(),
-    help="Session cache directory.")
+Subscribe a client to one or all apis.
 
-if __name__ == "__main__":
-    args = parser.parse_args()
+ Options:
+  -u, --apiusername    API username
+  -p, --apipassword    API password
+  -N, --apiName        The name of the API to subscribe the client application to.
+                       Use a wildcard to subscribe to all APIs
+  -T, --tier           The subscription tier
+  -R, --apiVersion     The version of the API to subscribe the client application to
+  -P, --apiProvider    The user who registered the API
+  -H, --hosturl        URL of the service
+  -d, --development    Run in dev mode using default dev server
+  -f, --force          Skip all user interaction
+  -i, --interactive    Prompt for values
+  -q, --quiet          Quiet (no output)
+  -v, --verbose        Verbose output
+  -V, --veryverbose    Very verbose output
+  -h, --help           Display this help and exit
+      --version        Output version information and exit
+"
+}
 
-    cache_dir = args.cachedir
-    client_name = args.name
-    api_name = args.apiname
-    api_version = args.apiversion
-    api_provider = args.apiprovider
-    username = args.username
-    password = args.password
-    tenantid = args.tenant
+##################################################################
+##################################################################
+#						Begin Script Logic						 #
+##################################################################
+##################################################################
 
-    agave = Agave()
-    context = utils.bootstrap_context(
-        cache_dir, tenantid=tenantid, username=username)
-    agave = Agave(tenant_id=context['tenantid'], username=context['username'])
-    agave.init()
+source "$DIR/clients-common.sh"
 
-    # Subscribe Oauth client to api.
-    try:
-        agave.clients_subscribe(
-            api_name, api_version, api_provider, client_name=client_name,
-            password=password, quiet=False)
-    except Exception as err:
-        print(err)
-        sys.exit(1)
+main() {
+	#echo -n
+	#set -x
+
+	if [ -z "$args" ]; then
+		err "Please specify a valid client name"
+	else
+
+		if [ -z "$apiName" ]; then
+			err "Please specify an API name or * for all APIs"
+		fi
+
+		if [ -z "$tier" ]; then
+			tier='Unlimited'
+		fi
+
+		cmd="curl -sku \"${apiusername}:xxxx\" -X POST -d \"apiName=${apiName}&tier=${tier}&apiVersion=${apiVersion}&apiProvider=${apiProvider}\" '${hosturl}${args}/subscriptions?pretty=true'"
+
+		if ((veryverbose)); then
+			[ "$piped" -eq 0 ] && log "Calling $cmd"
+		fi
+
+		response=`curl -sku "${apiusername}:${apipassword}" -X POST -d "apiName=${apiName}&tier=${tier}&apiVersion=${apiVersion}&apiProvider=${apiProvider}" "${hosturl}${args}/subscriptions?pretty=true"`
+
+		if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+			result=$(format_api_json "$response")
+			success "${result}"
+		else
+			errorresponse=$(jsonquery "$response" "message")
+			err "$errorresponse"
+		fi
+	fi
+}
+
+format_api_json() {
+
+	if ((veryverbose)); then
+		json_prettyify "${1}"
+	elif [[ $verbose -eq 1 ]]; then
+		result=$(jsonquery "$1" "result" 1)
+		json_prettyify "${result}"
+	else
+		result=$(jsonquery "$1" "result.[].apiName")
+		echo "${result}"
+	fi
+}
+
+##################################################################
+##################################################################
+#						End Script Logic						 #
+##################################################################
+##################################################################
+
+# }}}
+
+# Parse command line options
+source "$DIR/options.sh"
+
+
+# Main loop {{{
+
+# Print help if no arguments were passed.
+[[ $# -eq 0 ]] && set -- "-i"
+
+# Read the options and set stuff
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; safe_exit ;;
+    --version) version; copyright; disclaimer; safe_exit ;;
+    -u|--apiusername) shift; apiusername=$1 ;;
+    -p|--apipassword) shift; apipassword=$1 ;;
+    -N|--apiName) shift; apiName=$1 ;;
+  	-T|--tier) shift; tier=$1 ;;
+  	-P|--apiProvider) shift; apiProvider=$1 ;;
+  	-R|--apiVersion) shift; apiVersion=$1 ;;
+    -H|--hosturl) shift; hosturl=$1;;
+  	-d|--development) development=1 ;;
+    -v|--verbose) verbose=1 ;;
+    -V|--veryverbose) veryverbose=1; verbose=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -i|--interactive) interactive=1 ;;
+    -f|--force) force=1 ;;
+    --endopts) shift; break ;;
+    *) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+# Store the remaining part as arguments.
+args+=("$@")
+
+# }}}
+
+# Run the script logic
+source "$DIR/runner.sh"
