reverting the files commands from python to bash

diff --git a/bin/files-import b/bin/files-import
--- a/bin/files-import
+++ b/bin/files-import
@@ -1,66 +1,167 @@
-#!/usr/bin/env python
-"""
-    Usage: files-import [OPTIONS] SOURCE_URL agave://SYSTEM/PATH
+#!/bin/bash
+#
+# files-import
+#
+# author: opensource@tacc.cloud
+#
+# This script is part of the Agave API command line interface (CLI).
+# Import a file given by a remote url into a registered system.
+#
 
-Imports contents of a URL to a Tapis storage system. The subsequent staging will be
-done via a proxy between the native data protocol of the remote system and
-the URL. When possible, 3rd party transfer will take place. If no
-system id is specified, the user's default storage system will be used.
-This action is non-blocking.
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-Flags:
+source "$DIR/common.sh"
+
+# Script logic -- TOUCH THIS {{{
+
+# A list of all variables to prompt in interactive mode. These variables HAVE
+# to be named exactly as the longname option definition in usage().
+interactive_opts=(apisecret apikey urltoingest)
+
+# Print usage
+usage() {
+  echo -n "$(basename $0) [OPTION]... [PATH]
+
+Imports a remote URI to a remote storage system. The subsequent staging will be
+done via a proxy between the native data protocol of the remote system and the URL.
+When possible, 3rd party transfer will take place. If the given file type requires
+import filtering, it will be applied prior to the callback being sent. If no
+system id is specified, the user's default storage system will be used. This action
+is non-blocking.
+
+ Options:
+  -z, --access_token    Access token
+  -U, --urltoingest     The url to be imported
+  -W, --webhook         The email address or webhook to notify upon completion
+                        of all import filtering
+  -T, --filetype        The filetype associated with this file. See transforms-list
+                        for a full list of supported file types. Defaults to 'raw'
+  -N, --filename        The name of the file once uploaded
+  -S, --systemid        The system to which the file or folder will be uploaded
+      --filter          Comma separated list of fields to return in the response
+  -H, --hosturl         URL of the service
+  -d, --development     Run in dev mode using default dev server
+  -f, --force           Skip all user interaction
+  -i, --interactive     Prompt for values
+  -q, --quiet           Quiet (no output)
+  -v, --verbose         Verbose output
+  -V, --veryverbose     Very verbose output
   -h, --help            Display this help and exit
-"""
-from __future__ import print_function
-import argparse
-import sys
-from argparse import RawTextHelpFormatter
-from agavepy.agave import Agave
-from agavepy import utils
+      --version         Output version information and exit
+"
+}
 
-parser = argparse.ArgumentParser(formatter_class=RawTextHelpFormatter,
-                                 description="Imports contents of a URI to a Tapis storage system.\n" +
-                                 "Source URL must be publicly accessible or include HTTP \n" +
-                                 "Basic Authentication credentials. The destination must be\n" +
-                                 " an Agave-formatted URI to which the user has write access. ")
+##################################################################
+##################################################################
+#						Begin Script Logic						 #
+##################################################################
+##################################################################
 
-parser.add_argument(
-    "-c",
-    "--cachedir",
-    default=utils.credentials_cache_dir(),
-    help="Session cache directory.")
+source "$DIR/files-common.sh"
 
-parser.add_argument(
-    "source",
-    action="store",
-    help="Source URL")
+main() {
+	#echo -n
+	#set -x
 
-parser.add_argument(
-    "destination",
-    action="store",
-    help="Destination (prefix with agave://)")
+	local post_options='';
 
-if __name__ == "__main__":
-    try:
-        args = parser.parse_args()
-        cache_dir = args.cachedir
-        source = args.source
-        destination = args.destination
+  webhook_post_options=''
+	if [ -n "$webhook" ]; then
+    webhook=$(echo "$webhook" | sed 's/\&/%26/g' )
+    webhook_post_options="--data-urlencode 'notifications=${webhook}'"
+	fi
 
-        agave = Agave()
-        agave.load_client(cache_dir)
+  filetype_post_options=''
+	if [ -n "$filetype" ]; then
+		filetype_post_options="--data-urlencode 'fileType=${filetype}'"
+	fi
 
-        # Refresh tokens if necessary.
-        agave.refresh_tokens()
-        # Save out session cache
-        if agave.client_name is not None:
-            agave.save_configs(cache_dir)
+  filename_post_options=''
+	if [ -n "$filename" ]; then
+		filename_post_options=$"--data-urlencode "fileName=${filename}""
+	fi
 
-        # Import file.
-        destination = destination[len("agave://"):]
-        agave.files_import(source, destination)
-        sys.exit(0)
+	if [ -n "$systemid" ]; then
+		hosturl="${hosturl}media/system/${systemid}/"
+	else
+		hosturl="${hosturl}media/"
+	fi
 
-    except Exception as err:
-        print(err)
-        sys.exit(1)
+	cmd="curl -sk -H \"${authheader}\" -X POST --data-urlencode \"urlToIngest=${urltoingest}\" --data-urlencode \"notifications=${webhook}\" --data-urlencode \"fileType=${filetype}\" --data-urlencode \"fileName=${filename}\" '$hosturl$args?pretty=true'"
+
+  if ((veryverbose)); then
+      [ "$piped" -eq 0 ] && log "Calling $cmd"
+  fi
+
+  response=`curl -sk -H "${authheader}" -X POST --data-urlencode "urlToIngest=${urltoingest}" --data-urlencode "notifications=${webhook}" --data-urlencode "fileName=${filename}" --data-urlencode "fileType=${filetype}" --data-urlencode "fileName=${filename}" "$hosturl$args?pretty=true"`
+
+	if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+		result=$(format_api_json "$response")
+		success "$result"
+	else
+		errorresponse=$(jsonquery "$response" "message")
+		err "$errorresponse"
+	fi
+}
+
+format_api_json() {
+
+	if ((veryverbose)); then
+		echo "$1"
+	elif [[ $verbose -eq 1 ]]; then
+		result=$(jsonquery "$1" "result" 1)
+		json_prettyify "${result}"
+	else
+		echo "Successfully submitted ${urltoingest} for import"
+	fi
+}
+
+##################################################################
+##################################################################
+#						End Script Logic						 #
+##################################################################
+##################################################################
+
+# }}}
+
+# Parse command line options
+source "$DIR/options.sh"
+
+
+# Main loop {{{
+
+# Print help if no arguments were passed.
+[[ $# -eq 0 ]] && set -- "-i"
+
+# Read the options and set stuff
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; safe_exit ;;
+    --version) version; copyright; disclaimer; safe_exit ;;
+    -z|--access_token) shift; access_token=$1 ;;
+    -U|--urltoingest) shift; urltoingest=$1 ;;
+    -W|--webhook) shift; webhook=$1 ;;
+    -T|--filetype) shift; filetype=$1 ;;
+    -N|--filename) shift; filename=$1 ;;
+    -S|--systemid) shift; systemid=$1 ;;
+    --filter) shift; responsefilter=$1 ;;
+    -H|--hosturl) shift; hosturl=$1;;
+  	-d|--development) development=1 ;;
+    -v|--verbose) verbose=1 ;;
+    -V|--veryverbose) veryverbose=1; verbose=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -i|--interactive) interactive=1 ;;
+    -f|--force) force=1 ;;
+    --endopts) shift; break ;;
+    *) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+# Store the remaining part as arguments.
+args+=("$@")
+
+# }}}
+
+# Run the script logic
+source "$DIR/runner.sh"
diff --git a/bin/files-list b/bin/files-list
--- a/bin/files-list
+++ b/bin/files-list
@@ -1,60 +1,215 @@
-#!/usr/bin/env python
-"""
-    Usage: files-list [OPTIONS] agave://SYSTEM/PATH
+#!/bin/bash
+#
+# files-list
+#
+# author: opensource@tacc.cloud
+#
+# This script is part of the Agave API command line interface (CLI).
+# It retrieves a file listing on a remote system. If no  jobs. Optionally, one can search by name, tag,
+# ontology, or start date
+#
 
-Lists files on a Tapis storage system.
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-The path must be specified as an agave URI.
-Example:
-    files-list -l agave://tacc-data-user/path/to/dir
+source "$DIR/common.sh"
 
- Flags:
-  -c, --cachedir    Session cache directory.
-  -l, --long        Use long listing format
-"""
-from __future__ import print_function
-import argparse
-import sys
-from agavepy.agave import Agave
-from agavepy import utils
+# Script logic -- TOUCH THIS {{{
 
-parser = argparse.ArgumentParser(
-    description="Lists files on a Tapis storage system. The path must be specified as an agave URI (i.e. agave://tacc-data-user/path/to/dir)")
+# A list of all variables to prompt in interactive mode. These variables HAVE
+# to be named exactly as the longname option definition in usage().
+interactive_opts=(apisecret apikey)
 
-parser.add_argument(
-    "-c",
-    "--cachedir",
-    default=utils.credentials_cache_dir(),
-    help="Session cache directory.")
+# Print usage
+usage() {
+  echo -n "$(basename $0) [OPTION]... [PATH]
 
-parser.add_argument(
-    "-l", "--long", action="store_true", help="Use long listing format.")
+List files on a remote system. If no system is specified, your default storage
+system will be used. By specifying a system, the path given will be resolved
+on that remote system. Note that the system id, not hostname must be given.
 
-parser.add_argument("filepath", help="Path to list")
+ Options:
+  -z, --access_token    Access token
+  -S, --systemId        Specify the system id
+  -L, --long            Print response in unix-style ls -l format
+  -l, --limit           Maximum number of results to return
+  -o, --offset          Number of results to skip from the start
+      --filter          Comma separated list of fields to return in the response
+  -H, --hosturl         URL of the service
+  -d, --development     Run in dev mode using default dev server
+  -f, --force           Skip all user interaction
+  -i, --interactive     Prompt for values
+  -q, --quiet           Quiet (no output)
+  -v, --verbose         Verbose output
+  -V, --veryverbose     Very verbose output
+  -h, --help            Display this help and exit
+      --version         Output version information and exit
+      --rich            Provide rich response
+"
+}
 
-if __name__ == "__main__":
-    try:
-        args = parser.parse_args()
+##################################################################
+##################################################################
+#						Begin Script Logic						 #
+##################################################################
+##################################################################
 
-        cache_dir = args.cachedir
-        long_format = args.long
-        uri = args.filepath
-        agave = Agave()
-        agave.load_client(cache_dir)
+source "$DIR/files-common.sh"
 
-        # Refresh tokens if necessary.
-        agave.refresh_tokens()
-        # Save out session cache
-        if agave.client_name is not None:
-            agave.save_configs(cache_dir)
+main() {
+	#echo -n
+	#set -x
 
-        # Obtain uri - remove the prefix 'agave://'.
-        uri = uri[len("agave://"):]
+	if [ -n "$systemId" ]; then
+		hosturl="${hosturl}listings/system/${systemId}/${args}"
+	else
+		hosturl="${hosturl}listings/${args}"
+	fi
 
-        # List files on remote system.
-        agave.files_list(uri, long_format=long_format)
-        sys.exit(0)
+	cmd="curl -sk -H \"${authheader}\" '${hosturl}?pretty=true$(pagination)'"
 
-    except Exception as err:
-        print(err)
-        sys.exit(1)
+	if ((veryverbose)); then
+		[ "$piped" -eq 0 ] && log "Calling $cmd"
+	fi
+
+	response=`curl -sk -H "${authheader}" "${hosturl}?pretty=true$(pagination)"`
+
+	if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+		result=$(format_api_json "$response")
+#		success "$result"
+    echo "$result";
+	else
+		errorresponse=$(jsonquery "$response" "message")
+		err "$errorresponse"
+	fi
+
+
+}
+
+format_api_json() {
+
+	if ((veryverbose)); then
+		json_prettyify "${1}"
+	elif [[ $verbose -eq 1 ]]; then
+		result=$(jsonquery "$1" "result" 1)
+		json_prettyify "${result}"
+	elif [[ $long -eq 1 ]]; then
+        #lstng=$(lsify "$1" | awk '{ printf("%-10s %+12s %+18s %+32s %s\n", $1, $2, $3, $4, $5); }')
+        lsify "$1" | column -t -s$'\t'
+	elif [[ $rich -eq 1 ]]; then
+        result=$(richify "$1")
+        columnize "${result}"
+    else
+        result=$(jsonquery "$1" "result.[].name")
+        echo "${result}"
+	fi
+}
+
+lsify () {
+    #jq '.result[] | {type,length,name,lastModified}'
+
+    names=($(jsonquery "$1" "result.[].name"))
+    #echo $names
+    lengths=($(jsonquery "$1" "result.[].length"))
+    #echo $lengths
+    types=($(jsonquery "$1" "result.[].type"))
+    #echo $types
+    modifieds=($(jsonquery "$1" "result.[].lastModified"))
+    #echo $modifieds
+    pems=($(jsonquery "$1" "result.[].permissions"))
+    thisyear=$(date +%Y)
+
+    n=0
+    for i in "${names[@]}"; do
+        up=''
+        if [[ "${pems[$n]}" == "ALL" ]]; then
+            up='rwx------'
+        elif [[ "${pems[$n]}" == "READ" ]]; then
+            up='r--------'
+        elif [[ "${pems[$n]}" == "WRITE" ]]; then
+            up='-w-------'
+        elif [[ "${pems[$n]}" == "EXECUTE" ]]; then
+            up='--x------'
+        elif [[ "${pems[$n]}" == "READ_WRITE" ]]; then
+            up='rw-------'
+        elif [[ "${pems[$n]}" == "READ_EXECUTE" ]]; then
+            up='r-x------'
+        elif [[ "${pems[$n]}" == "WRITE_EXECUTE" ]]; then
+            up='-wx------'
+        elif [[ "${pems[$n]}" == "EXECUTE" ]]; then
+            up='--x------'
+        fi
+
+        if [[ "${types[$n]}" == "dir" ]]; then
+            up="d${up}"
+        else
+            up="-${up}"
+        fi
+
+        formatteddate=$(format_iso8601_time "${modifieds[$n]}")
+        echo -e "${up}\t${username}\t${lengths[$n]}\t${formatteddate}\t$i"
+
+#        moddate=($(echo ${modifieds[$n]} | sed -e 's/T.*//' -e 's/-/ /g'))
+#        tmon=$(month_of_year ${moddate[1]})
+#        tday=$(echo ${moddate[1]} | sed 's/^0*//')
+
+#        if [[ $thisyear = ${moddate[0]} ]]; then
+#            modtime=$(echo ${modifieds[$n]} | sed -e 's/.*T//' -e 's/\:..\....-..\:..//')
+#            echo -e "${up}\t${username}\t${lengths[$n]}\t${modtime}\t$i"
+#        else
+#            echo -e "${up}\t${username}\t${lengths[$n]}\t${tmon}\t${tday}\t${moddate[0]}\t$i"
+#        fi
+#        tmod=`date -d "$(echo ${modifieds[$n]} | sed -e 's/T//' -e 's/.000-05\:00\:00//' | sed -e )"`
+#        echo -e "${up}\t${username}\t${lengths[$n]}\t${tmod}\t$i"
+        n=$[n+1]
+    done
+
+}
+
+##################################################################
+##################################################################
+#						End Script Logic						 #
+##################################################################
+##################################################################
+
+# }}}
+
+# Parse command line options
+source "$DIR/options.sh"
+
+# Main loop {{{
+
+# Print help if no arguments were passed.
+#[[ $# -eq 0 ]] && set -- "--help"
+
+# Read the options and set stuff
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; safe_exit ;;
+    --version) version; copyright; disclaimer; safe_exit ;;
+    -z|--access_token) shift; access_token=$1 ;;
+    -S|--systemId) shift; systemId=$1 ;;
+    -L|--long) long=1;;
+    -l|--limit) shift; limit=$1;;
+    -o|--offset) shift; offset=$1;;
+    --filter) shift; responsefilter=$1 ;;
+    -H|--hosturl) shift; hosturl=$1;;
+  	-d|--development) development=1 ;;
+    -v|--verbose) verbose=1 ;;
+    -V|--veryverbose) veryverbose=1; verbose=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -i|--interactive) interactive=1 ;;
+    -f|--force) force=1 ;;
+    --rich) rich=1 ;;
+    --endopts) shift; break ;;
+    *) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+# Store the remaining part as arguments.
+args+=("$@")
+
+# }}}
+
+# Run the script logic
+source "$DIR/runner.sh"
diff --git a/bin/files-mkdir b/bin/files-mkdir
--- a/bin/files-mkdir
+++ b/bin/files-mkdir
@@ -1,52 +1,138 @@
-#!/usr/bin/env python
-"""
-    Usage: files-mkdir [OPTIONS] agave://SYSTEM/PATH/NEW_DIR
+#!/bin/bash
+#
+# files-mkdir
+#
+# author: opensource@tacc.cloud
+#
+# This script is part of the Agave API command line interface (CLI).
+# It creates a new folder on a remote system.
+#
 
-Creates a directory on a Tapis storage system. Note that a system id, not a
-hostname must be given and thus the new path must be specified as an Agave uri (agave://).
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-Flags:
-    -h, --help            Display this help and exit
-"""
-from __future__ import print_function
-import argparse
-import sys
-from agavepy.agave import Agave
-from agavepy import utils
+source "$DIR/common.sh"
 
-parser = argparse.ArgumentParser(
-    description="Creates a directory on a Tapis storage system. The new path must be specified as an Agave URI (agave://system_id/destination/new_directory).")
+# Script logic -- TOUCH THIS {{{
 
-parser.add_argument(
-    "-c",
-    "--cachedir",
-    default=utils.credentials_cache_dir(),
-    help="Session cache directory.")
+# A list of all variables to prompt in interactive mode. These variables HAVE
+# to be named exactly as the longname option definition in usage().
+interactive_opts=(apisecret apikey, name)
 
-parser.add_argument(
-    "destination",
-    action="store",
-    help="Directory to make (Prefix with 'agave://')")
+# Print usage
+usage() {
+  echo -n "$(basename $0) [OPTION]... [PATH]
 
-if __name__ == "__main__":
-    try:
-        args = parser.parse_args()
-        cache_dir = args.cachedir
-        destination = args.destination
+Create a folder on a remote system. If no system is specified, your default storage
+system will be used. By specifying a system, the path given will be resolved
+on that remote system. Note that the system id, not hostname must be given.
 
-        agave = Agave()
-        agave.load_client(cache_dir)
+ Options:
+  -z, --access_token    Access token
+  -S, --systemId        Specify the system id
+  -N, --name            Name of the new folder
+      --filter          Comma separated list of fields to return in the response
+  -H, --hosturl         URL of the service
+  -d, --development     Run in dev mode using default dev server
+  -f, --force           Skip all user interaction
+  -i, --interactive     Prompt for values
+  -q, --quiet           Quiet (no output)
+  -v, --verbose         Verbose output
+  -V, --veryverbose     Very verbose output
+  -h, --help            Display this help and exit
+      --version         Output version information and exit
+"
+}
 
-        # Refresh tokens if necessary.
-        agave.refresh_tokens()
-        # Save out session cache
-        if agave.client_name is not None:
-            agave.save_configs(cache_dir)
+##################################################################
+##################################################################
+#						Begin Script Logic						 #
+##################################################################
+##################################################################
 
-        destination = destination[len("agave://"):]
-        agave.files_mkdir(destination)
-        sys.exit(0)
+source "$DIR/files-common.sh"
 
-    except Exception as err:
-        print(err)
-        sys.exit(1)
+main() {
+	#echo -n
+	#set -x
+
+	if [ -n "$systemId" ]; then
+		hosturl="${hosturl}media/system/${systemId}/"
+	else
+		hosturl="${hosturl}media/"
+	fi
+
+	cmd="curl -sk -H \"${authheader}\" -X PUT -d \"action=mkdir&path=${name}\" '${hosturl}${args}?pretty=true'"
+
+	if ((veryverbose)); then
+			[ "$piped" -eq 0 ] && log "Calling $cmd"
+		fi
+
+	response=`curl -sk -H "${authheader}" -X PUT -d "action=mkdir&path=${name}" "${hosturl}${args}?pretty=true"`
+
+	if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+		result=$(format_api_json "$response")
+		success "$result"
+	else
+		errorresponse=$(jsonquery "$response" "message")
+		err "$errorresponse"
+	fi
+}
+
+format_api_json() {
+
+	if ((veryverbose)); then
+		echo "$1"
+	elif [[ $verbose -eq 1 ]]; then
+		result=$(jsonquery "$1" "result" 1)
+		json_prettyify "${result}"
+	else
+        newfolder=${path%/}${name}
+        echo "Successfully created folder ${newfolder}"
+	fi
+}
+
+##################################################################
+##################################################################
+#						End Script Logic						 #
+##################################################################
+##################################################################
+
+# }}}
+
+# Parse command line options
+source "$DIR/options.sh"
+
+# Main loop {{{
+
+# Print help if no arguments were passed.
+#[[ $# -eq 0 ]] && set -- "--help"
+
+# Read the options and set stuff
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; safe_exit ;;
+    --version) version; copyright; disclaimer; safe_exit ;;
+    -z|--access_token) shift; access_token=$1 ;;
+    -S|--systemId) shift; systemId=$1 ;;
+    -N|--name) shift; name=$1 ;;
+    --filter) shift; responsefilter=$1 ;;
+    -H|--hosturl) shift; hosturl=$1;;
+  	-d|--development) development=1 ;;
+    -v|--verbose) verbose=1 ;;
+    -V|--veryverbose) veryverbose=1; verbose=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -i|--interactive) interactive=1 ;;
+    -f|--force) force=1 ;;
+    --endopts) shift; break ;;
+    *) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+# Store the remaining part as arguments.
+args+=("$@")
+
+# }}}
+
+# Run the script logic
+source "$DIR/runner.sh"
diff --git a/bin/files-pems-delete b/bin/files-pems-delete
--- a/bin/files-pems-delete
+++ b/bin/files-pems-delete
@@ -1,54 +1,146 @@
-#!/usr/bin/env python
-"""
-    Usage: files-pems-delete [OPTIONS] agave://SYSTEM/SOURCE agave://SYSTEM/DESTINATION
+#!/bin/bash
+#
+# files-pems-list
+#
+# author: opensource@tacc.cloud
+#
+# This script is part of the Agave API command line interface (CLI).
+# It provides a mechanism for setting user permissions on a file or folder.
+#
 
-Remove all user permissions (except those of the owner) from a file or directory.
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-Flags:
+source "$DIR/common.sh"
+
+# Script logic -- TOUCH THIS {{{
+
+# A list of all variables to prompt in interactive mode. These variables HAVE
+# to be named exactly as the longname option definition in usage().
+interactive_opts=(apisecret apikey username permission)
+
+# Print usage
+usage() {
+  echo -n "$(basename $0) [OPTION]... [PATH]
+
+Remove user permissions from a file or folder. For all but iRODS systems, these
+permissions are set at the API level and do not reflect *nix or other file
+system ACL. On iRODS systems, if the system.storageConfig.mirror attribute
+is set to true then any permissions set via the API will be mirrored onto
+the remote system.
+
+To recursively remove permissions, use the files-pems-update script setting the
+permission to NONE for each user. This script cannot perform recursive permission
+operations.
+
+ Options:
+  -z, --access_token    Access token
+  -S, --systemId        Specify the system id
+  -H, --hosturl         URL of the service
+  -d, --development     Run in dev mode using default dev server
+  -f, --force           Skip all user interaction
+  -i, --interactive     Prompt for values
+  -q, --quiet           Quiet (no output)
+  -v, --verbose         Verbose output
+  -V, --veryverbose     Very verbose output
   -h, --help            Display this help and exit
-"""
-from __future__ import print_function
-import argparse
-import sys
-from agavepy.agave import Agave
-from agavepy import utils
+      --version         Output version information and exit
+"
+}
 
-parser = argparse.ArgumentParser(
-    description="Remove all user permissions (except those of the owner) from a file or directory."
-)
+##################################################################
+##################################################################
+#						Begin Script Logic						 #
+##################################################################
+##################################################################
 
-parser.add_argument(
-    "-c",
-    "--cachedir",
-    default=utils.credentials_cache_dir(),
-    help="Session cache directory.")
+source "$DIR/files-common.sh"
 
-parser.add_argument(
-    "filepath", help="Path where permissions should be deleted")
+main() {
+	#echo -n
+	#set -x
 
-if __name__ == "__main__":
-    try:
-        args = parser.parse_args()
+	if [ -z "$args" ]; then
+		err "Please specify a valid file path for which to retrieve permissions"
+	else
 
-        cache_dir = args.cachedir
-        uri = args.filepath
+		if [ -n "$systemId" ]; then
+			hosturl="${hosturl}pems/system/${systemId}/"
+		else
+			hosturl="${hosturl}pems/"
+		fi
 
-        agave = Agave()
-        agave.load_client(cache_dir)
+    cmd="curl -sk -H \"${authheader}\" -X DELETE '${hosturl}${args}?pretty=true'"
 
-        # Refresh tokens if necessary.
-        agave.refresh_tokens()
-        # Save out session cache
-        if agave.client_name is not None:
-            agave.save_configs(cache_dir)
+		if ((veryverbose)); then
+			[ "$piped" -eq 0 ] && log "Calling $cmd"
+		fi
 
-        # Obtain uri - remove the prefix 'agave://'.
-        uri = uri[len("agave://"):]
+		response=`curl -sk -H "${authheader}" -X DELETE "${hosturl}${args}?pretty=true"`
 
-        # Delete all user's permissions.
-        agave.files_pems_delete(uri)
-        sys.exit(0)
+		if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+			result=$(format_api_json "$response")
+			success "$result"
+		else
+			errorresponse=$(jsonquery "$response" "message")
+			err "$errorresponse"
+		fi
+	fi
 
-    except Exception as err:
-        print(err)
-        sys.exit(1)
+}
+
+format_api_json() {
+
+	if ((veryverbose)); then
+		echo "$1"
+	elif [[ $verbose -eq 1 ]]; then
+		result=$(jsonquery "$1" "result" 1)
+		json_prettyify "${result}"
+	else
+		echo "Successfully removed all permissions on $hosturl"
+	fi
+}
+
+##################################################################
+##################################################################
+#						End Script Logic						 #
+##################################################################
+##################################################################
+
+# }}}
+
+# Parse command line options
+source "$DIR/options.sh"
+
+
+# Main loop {{{
+
+# Print help if no arguments were passed.
+#[[ $# -eq 0 ]] && set -- "--help"
+
+# Read the options and set stuff
+while [[ $1 = -?* ]]; do
+  case $1 in
+    -h|--help) usage >&2; safe_exit ;;
+    --version) version; copyright; disclaimer; safe_exit ;;
+    -z|--access_token) shift; access_token=$1 ;;
+    -S|--systemId) shift; systemId=$1 ;;
+    -H|--hosturl) shift; hosturl=$1;;
+  	-d|--development) development=1 ;;
+    -v|--verbose) verbose=1 ;;
+    -V|--veryverbose) veryverbose=1; verbose=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -i|--interactive) interactive=1 ;;
+    -f|--force) force=1 ;;
+    --endopts) shift; break ;;
+    *) die "invalid option: $1" ;;
+  esac
+  shift
+done
+
+# Store the remaining part as arguments.
+args+=("$@")
+
+# }}}
+
+# Run the script logic
+source "$DIR/runner.sh"
