removed depricated commands and updated jobs-hide and jobs-unhide

diff --git a/bin/jobs-unhide b/bin/jobs-unhide
--- a/bin/jobs-unhide
+++ b/bin/jobs-unhide
@@ -1,12 +1,11 @@
 #!/bin/bash
 #
-# jobs-kick
+# jobs-unhide
 #
 # author: opensource@tacc.cloud
 #
 # This script is part of the Agave API command line interface (CLI).
-# It resets a job's status by rolling it back to a previous state and
-# resubmitting it to the work queue.
+# It restores a job from a hidden status
 #
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -21,13 +20,9 @@ interactive_opts=(apisecret apikey)
 
 # Print usage
 usage() {
-  echo -n "$(basename $0) [OPTION]... JOB_ID...
+    echo -n "$(basename $0) [OPTION]... JOB_ID...
 
-Rolls a job back to the previous state and returns it to the processing queue.
-Without going into details of the plumbing behind the scenes, this works similar
-to kicking a vending machine when your purchase is stuck. It works pretty well
-most times, but there will always be some situations where your job is too jammed
-up to resolve this way and you are better off just stopping and deleting it.
+Restores a job from a hidden state to visible and available for interaction.
 
  Options:
   -z, --access_token    Access token
@@ -53,23 +48,23 @@ up to resolve this way and you are better off just stopping and deleting it.
 source "$DIR/jobs-common.sh"
 
 main() {
-	#echo -n
-	#set -x
+    #echo -n
+    #set -x
 
-	hosturl=${hosturl%/}
-	if [ -z "$args" ]; then
-		err "Please specify one or more valid job ids to kick"
-	else
+    hosturl=${hosturl%/}
+    if [ -z "$args" ]; then
+        err "Please specify one or more valid job ids to unhide"
+    else
 
         for jobid in "${args[@]}"
         do
-            cmd="curl -sk -H \"${authheader}\" -H \"Content-Type: application/json\" -X POST --data-binary '{\"action\": \"reset\"}' '$hosturl/$jobid?pretty=true$(pagination)'"
+            cmd="curl -sk -H \"${authheader}\" -H \"Content-Type: application/json\" -X POST '$hosturl/$jobid/unhide?pretty=true'"
 
             if ((veryverbose)); then
                 [ "$piped" -eq 0 ] && log "Calling $cmd"
             fi
 
-            response=`curl -sk -H "${authheader}" -H "Content-Type: application/json" -X POST --data-binary '{"action":"reset"}' "$hosturl/$jobid?pretty=true"`
+            response=`curl -sk -H "${authheader}" -H "Content-Type: application/json" -X POST "$hosturl/$jobid/unhide?pretty=true"`
 
             if [[ $(jsonquery "$response" "status") = 'success' ]]; then
                 result=$(format_api_json "$response")
@@ -79,21 +74,21 @@ main() {
                 err "$errorresponse"
             fi
         done
-	fi
+    fi
 }
 
 format_api_json() {
 
-  if ((veryverbose)); then
-		echo "$1"
-	elif [[ $verbose -eq 1 ]]; then
-		result=$(jsonquery "$1" "result" 1)
-		json_prettyify "${result}"
-	else
-		jobstatus=$(jsonquery "$1" "result.status")
+    if ((veryverbose)); then
+        echo "$1"
+    elif [[ $verbose -eq 1 ]]; then
+        result=$(jsonquery "$1" "result" 1)
+        json_prettyify "${result}"
+    else
+        jobstatus=$(jsonquery "$1" "result.status")
         jobid=$(jsonquery "$1" "result.id")
-		echo "Successfully kicked job $jobid. The current job status is now $jobstatus"
-	fi
+        echo "Successfully restored job $jobid."
+    fi
 }
 
 ##################################################################
@@ -114,22 +109,22 @@ source "$DIR/options.sh"
 
 # Read the options and set stuff
 while [[ $1 = -?* ]]; do
-  case $1 in
-    -h|--help) usage >&2; safe_exit ;;
-    --version) version; copyright; disclaimer; safe_exit ;;
-    -z|--access_token) shift; access_token=$1 ;;
-    --filter) shift; responsefilter=$1 ;;
-    -H|--hosturl) shift; hosturl=$1;;
-  	-d|--development) development=1 ;;
-    -v|--verbose) verbose=1 ;;
-    -V|--veryverbose) veryverbose=1; verbose=1 ;;
-    -q|--quiet) quiet=1 ;;
-    -i|--interactive) interactive=1 ;;
-    -f|--force) force=1 ;;
-    --endopts) shift; break ;;
-    *) die "invalid option: $1" ;;
-  esac
-  shift
+    case $1 in
+        -h|--help) usage >&2; safe_exit ;;
+        --version) version; copyright; disclaimer; safe_exit ;;
+        -z|--access_token) shift; access_token=$1 ;;
+        --filter) shift; responsefilter=$1 ;;
+        -H|--hosturl) shift; hosturl=$1;;
+        -d|--development) development=1 ;;
+        -v|--verbose) verbose=1 ;;
+        -V|--veryverbose) veryverbose=1; verbose=1 ;;
+        -q|--quiet) quiet=1 ;;
+        -i|--interactive) interactive=1 ;;
+        -f|--force) force=1 ;;
+        --endopts) shift; break ;;
+        *) die "invalid option: $1" ;;
+    esac
+    shift
 done
 
 # Store the remaining part as arguments.
