Fixed two additional cases where the expectation that the CLI is in the path would cause failures if it was not

diff --git a/bin/jobs-submit b/bin/jobs-submit
--- a/bin/jobs-submit
+++ b/bin/jobs-submit
@@ -8,7 +8,7 @@
 # It submits a job for execution by the API.
 #
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 source "$DIR/common.sh"
 
@@ -52,8 +52,8 @@ Submit a new job request.
 source "$DIR/jobs-common.sh"
 
 main() {
-	#echo -n
-	#set -x
+  #echo -n
+  #set -x
 
   if [[ -z "$filetoupload" ]]; then
 
@@ -73,7 +73,7 @@ main() {
   else
 
     # reading from stdin
-    if [[ "$filetoupload" == "-"  ]]; then
+    if [[ "$filetoupload" == "-" ]]; then
 
       cmd="curl -sk -H \"${authheader}\" -H \"Content-Type: application/json\" -X POST --data-binary @- '$hosturl?pretty=true'"
 
@@ -82,7 +82,7 @@ main() {
       fi
 
       # make sure we specify content type as application/json
-      response=`curl -sk -H "${authheader}" -H "Content-Type: application/json" -X POST --data-binary @- "$hosturl?pretty=true"`
+      response=$(curl -sk -H "${authheader}" -H "Content-Type: application/json" -X POST --data-binary @- "$hosturl?pretty=true")
 
     # standard file upload
     else
@@ -93,11 +93,11 @@ main() {
         [ "$piped" -eq 0 ] && log "Calling $cmd"
       fi
 
-      response=`curl -sk -H "${authheader}" -H "Content-Type: application/json" -X POST -d "@$filetoupload" "$hosturl?pretty=true"`
+      response=$(curl -sk -H "${authheader}" -H "Content-Type: application/json" -X POST -d "@$filetoupload" "$hosturl?pretty=true")
 
     fi
 
-  	if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+    if [[ $(jsonquery "$response" "status") == 'success' ]]; then
 
       if ((watch)); then
 
@@ -119,36 +119,36 @@ main() {
           jhparams="$jhparams -v "
         fi
 
-        jobs-history $jhparams -W $jobwatchid
+        ${DIR}/jobs-history $jhparams -W $jobwatchid
 
       else
 
         result=$(format_api_json "$response")
-  		  success "$result"
+        success "$result"
 
       fi
 
     else
 
       errorresponse=$(jsonquery "$response" "message")
-  		err "$errorresponse"
+      err "$errorresponse"
 
-  	fi
+    fi
 
   fi
 }
 
 format_api_json() {
 
-	if ((veryverbose)); then
-		echo "$1"
-	elif [[ $verbose -eq 1 ]]; then
-		result=$(jsonquery "$1" "result" 1)
-		json_prettyify "${result}"
-	else
-		jobid=$(jsonquery "$1" "result.id")
-		echo "Successfully submitted job $jobid"
-	fi
+  if ((veryverbose)); then
+    echo "$1"
+  elif [[ $verbose -eq 1 ]]; then
+    result=$(jsonquery "$1" "result" 1)
+    json_prettyify "${result}"
+  else
+    jobid=$(jsonquery "$1" "result.id")
+    echo "Successfully submitted job $jobid"
+  fi
 }
 
 ##################################################################
@@ -162,30 +162,55 @@ format_api_json() {
 # Parse command line options
 source "$DIR/options.sh"
 
-
 # Main loop {{{
 
 # Print help if no arguments were passed.
 [[ $# -eq 0 ]] && set -- "-i"
 
 # Read the options and set stuff
-while [[ $1 = -?* ]]; do
+while [[ $1 == -?* ]]; do
   case $1 in
-    -h|--help) usage >&2; safe_exit ;;
-    --version) version; copyright; disclaimer; safe_exit ;;
-    -z|--access_token) shift; access_token=$1 ;;
-    -F|--filetoupload) shift; filetoupload=$1 ;;
-    -W| --watch) watch=1;;
-    --filter) shift; responsefilter=$1 ;;
-    -H|--hosturl) shift; hosturl=$1;;
-  	-d|--development) development=1 ;;
-    -v|--verbose) verbose=1 ;;
-    -V|--veryverbose) veryverbose=1; verbose=1 ;;
-    -q|--quiet) quiet=1 ;;
-    -i|--interactive) interactive=1 ;;
-    -f|--force) force=1 ;;
-    --endopts) shift; break ;;
-    *) die "invalid option: $1" ;;
+  -h | --help)
+    usage >&2
+    safe_exit
+    ;;
+  --version)
+    version
+    copyright
+    disclaimer
+    safe_exit
+    ;;
+  -z | --access_token)
+    shift
+    access_token=$1
+    ;;
+  -F | --filetoupload)
+    shift
+    filetoupload=$1
+    ;;
+  -W | --watch) watch=1 ;;
+  --filter)
+    shift
+    responsefilter=$1
+    ;;
+  -H | --hosturl)
+    shift
+    hosturl=$1
+    ;;
+  -d | --development) development=1 ;;
+  -v | --verbose) verbose=1 ;;
+  -V | --veryverbose)
+    veryverbose=1
+    verbose=1
+    ;;
+  -q | --quiet) quiet=1 ;;
+  -i | --interactive) interactive=1 ;;
+  -f | --force) force=1 ;;
+  --endopts)
+    shift
+    break
+    ;;
+  *) die "invalid option: $1" ;;
   esac
   shift
 done
diff --git a/bin/jobs-template b/bin/jobs-template
--- a/bin/jobs-template
+++ b/bin/jobs-template
@@ -8,7 +8,7 @@
 # It takes an app id as an argument and generates a job submission form.
 #
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 source "$DIR/common.sh"
 
@@ -54,12 +54,12 @@ job descriptions.
 source "$DIR/apps-common.sh"
 
 main() {
-	#echo -n
-	#set -x
+  #echo -n
+  #set -x
 
   if [ -z "$args" ]; then
     err "Please specify an app on which to base the job template"
-	else
+  else
 
     if ((development)); then
       debug_flag='-d'
@@ -73,7 +73,7 @@ main() {
         if ((verbose)); then
           [ "$piped" -eq 0 ] && log "Fetching app description for $args"
         fi
-        app_description=$(apps-list $debug_flag -v $args)
+        app_description=$(${DIR}/apps-list $debug_flag -v $args)
         kvset jtapp "$app_description"
       else
         app_description=$(kvget jtapp)
@@ -84,7 +84,7 @@ main() {
           kvdel jtapp
           kvdel jtexe
           kvdel jtstorage
-          app_description=$(apps-list $debug_flag -v $args)
+          app_description=$(${DIR}/apps-list $debug_flag -v $args)
           kvset jtapp "$app_description"
         else
           if ((verbose)); then
@@ -99,7 +99,7 @@ main() {
       kvdel jtapp
       kvdel jtexe
       kvdel jtstorage
-      app_description=$(apps-list $debug_flag -v $args)
+      app_description=$(${DIR}/apps-list $debug_flag -v $args)
     fi
 
     if ((veryverbose)); then
@@ -110,7 +110,7 @@ main() {
     # queue to fill in any missing default runtime configuration info in the
     # job template.
 
-    app_execution_system_id=$(apps-list $debug_flag -v --filter=executionSystem $args 2>/dev/null)
+    app_execution_system_id=$(${DIR}/apps-list $debug_flag -v --filter=executionSystem $args 2>/dev/null)
 
     execution_system_id=$(jsonquery "$app_execution_system_id" "executionSystem")
 
@@ -121,7 +121,7 @@ main() {
           if ((verbose)); then
             [ "$piped" -eq 0 ] && log "Fetching system description for execution system $execution_system_id..."
           fi
-          execution_system=`echo $(systems-list $debug_flag -v $execution_system_id)`
+          execution_system=$(echo $(${DIR}/systems-list $debug_flag -v $execution_system_id))
           kvset jtexe "$execution_system"
         else
           execution_system=$(kvget jtexe)
@@ -130,7 +130,7 @@ main() {
               [ "$piped" -eq 0 ] && log "Cached execution system description was stale. Fetching system description for execution system $execution_system_id..."
             fi
             kvdel jtexe
-            execution_system=$(systems-list $debug_flag -v $execution_system_id)
+            execution_system=$(${DIR}/systems-list $debug_flag -v $execution_system_id)
             kvset jtexe "$execution_system"
           else
             if ((verbose)); then
@@ -142,17 +142,15 @@ main() {
         if ((verbose)); then
           [ "$piped" -eq 0 ] && log "Fetching system description for execution system $execution_system_id..."
         fi
-        execution_system=`echo $(systems-list $debug_flag -v $execution_system_id)`
+        execution_system=$(echo $(${DIR}/systems-list $debug_flag -v $execution_system_id))
       fi
 
-
       # set -x
-      queue_names=(`jsonquery "${execution_system}" "queues.[].name"`)
+      queue_names=($(jsonquery "${execution_system}" "queues.[].name"))
       # set +x
-      queue_defaults=(`jsonquery "${execution_system}" "queues.[].default"`)
-      queue_memories=(`jsonquery "${execution_system}" "queues.[].maxMemoryPerNode"`)
-      queue_ppns=(`jsonquery "${execution_system}" "queues.[].maxProcessorsPerNode"`)
-
+      queue_defaults=($(jsonquery "${execution_system}" "queues.[].default"))
+      queue_memories=($(jsonquery "${execution_system}" "queues.[].maxMemoryPerNode"))
+      queue_ppns=($(jsonquery "${execution_system}" "queues.[].maxProcessorsPerNode"))
 
       for i in "${queue_defaults[@]}"; do
         if [ "$i" == 'rue' ] || [ "$i" == "true" ] || [ "$i" == "True" ]; then
@@ -201,7 +199,7 @@ main() {
           if ((verbose)); then
             [ "$piped" -eq 0 ] && log "Fetching default storage system description..."
           fi
-          default_system=$(systems-list $debug_flag -D -S -v )
+          default_system=$(systems-list $debug_flag -D -S -v)
           kvset jtstorage "$default_system"
         else
           default_system=$(kvget jtstorage)
@@ -210,7 +208,7 @@ main() {
               [ "$piped" -eq 0 ] && log "Cached storage system description was stale. Fetching fresh default storage system description..."
             fi
             kvdel jtstorage
-            default_system=$(systems-list $debug_flag -D -S -v )
+            default_system=$(systems-list $debug_flag -D -S -v)
             kvset jtstorage "$default_system"
           else
             if ((verbose)); then
@@ -222,7 +220,7 @@ main() {
         if ((verbose)); then
           [ "$piped" -eq 0 ] && log "Fetching default storage system description..."
         fi
-        default_system=$(systems-list $debug_flag -D -S -v )
+        default_system=$(systems-list $debug_flag -D -S -v)
       fi
 
       archivePath="null"
@@ -236,20 +234,19 @@ main() {
     if ((verbose)); then
       [ "$piped" -eq 0 ] && log "Parsing app inputs..."
     fi
-    input_ids=(`jsonquery "$app_description" "inputs.[].id"`)
-    input_defaults=(`jsonquery "$app_description" "inputs.[].value.default"`)
-    input_requireds=(`jsonquery "$app_description" "inputs.[].value.required"`)
-    input_visibles=(`jsonquery "$app_description" "inputs.[].value.visible"`)
-    input_min_cardinality=(`jsonquery "$app_description" "inputs.[].semantics.minCardinality"`)
-    input_max_cardinality=(`jsonquery "$app_description" "inputs.[].semantics.maxCardinality"`)
+    input_ids=($(jsonquery "$app_description" "inputs.[].id"))
+    input_defaults=($(jsonquery "$app_description" "inputs.[].value.default"))
+    input_requireds=($(jsonquery "$app_description" "inputs.[].value.required"))
+    input_visibles=($(jsonquery "$app_description" "inputs.[].value.visible"))
+    input_min_cardinality=($(jsonquery "$app_description" "inputs.[].semantics.minCardinality"))
+    input_max_cardinality=($(jsonquery "$app_description" "inputs.[].semantics.maxCardinality"))
     input_count=${#input_ids[@]}
-
 
     n=0
     for i in "${input_ids[@]}"; do
 
       # figure out fencepost comma problem
-      if [[ "$input_count" -eq "$[n+1]" ]]; then
+      if [[ "$input_count" -eq "$((n + 1))" ]]; then
         trailingcomma=''
       else
         trailingcomma=','
@@ -258,10 +255,10 @@ main() {
       if [[ "${input_visibles[$n]}" == "rue" ]] || [[ "${input_visibles[$n]}" == "true" ]]; then
         if [[ "${input_requireds[$n]}" == "rue" ]] || [[ "${input_requireds[$n]}" == "true" ]] || [[ "$allfields" == 1 ]]; then
           if [[ "${input_defaults[$n]}" == "null" ]]; then
-            tmpDefaults=( $(generateDefaults "input" ${input_min_cardinality[$n]} ${input_max_cardinality[$n]}) )
+            tmpDefaults=($(generateDefaults "input" ${input_min_cardinality[$n]} ${input_max_cardinality[$n]}))
             tmpDefaultsCount=${#tmpDefaults[@]}
           elif [[ "${input_max_cardinality[$n]}" -ne 1 ]]; then
-            tmpDefaults=( $(echo ${input_defaults[$n]} | sed 's/\[//g' | sed 's/\]//g' | sed 's/,/ /g') )
+            tmpDefaults=($(echo ${input_defaults[$n]} | sed 's/\[//g' | sed 's/\]//g' | sed 's/,/ /g'))
             tmpDefaultsCount=${#tmpDefaults[@]}
           fi
 
@@ -272,13 +269,13 @@ main() {
             zz=0
             for z in "${tmpDefaults[@]}"; do
               tc=','
-              if [[ "$tmpDefaultsCount" -eq "$[zz+1]" ]]; then
+              if [[ "$tmpDefaultsCount" -eq "$((zz + 1))" ]]; then
                 tc=''
               fi
               if [[ "$z" != "null" ]]; then
                 inputs=$(printf "%s\n      \"%s\"%s" "$inputs" "$z" "$tc")
               fi
-              zz=$[zz+1]
+              zz=$((zz + 1))
             done
 
             inputs=$(printf "%s\n    ]%s" "$inputs" "$trailingcomma")
@@ -290,7 +287,7 @@ main() {
         fi
       fi
 
-      n=$[n+1]
+      n=$((n + 1))
 
     done
 
@@ -301,13 +298,13 @@ main() {
     if ((verbose)); then
       [ "$piped" -eq 0 ] && log "Parsing app parameters..."
     fi
-    parameter_ids=(`jsonquery "$app_description" "parameters.[].id"`)
-    parameter_defaults=(`jsonquery "$app_description" "parameters.[].value.default"`)
-    parameter_requireds=(`jsonquery "$app_description" "parameters.[].value.required"`)
-    parameter_visibles=(`jsonquery "$app_description" "parameters.[].value.visible"`)
-    parameter_types=(`jsonquery "$app_description" "parameters.[].value.type"`)
-    parameter_min_cardinality=(`jsonquery "${app_description}" "parameters.[].semantics.minCardinality"`)
-    parameter_max_cardinality=(`jsonquery "${app_description}" "parameters.[].semantics.maxCardinality"`)
+    parameter_ids=($(jsonquery "$app_description" "parameters.[].id"))
+    parameter_defaults=($(jsonquery "$app_description" "parameters.[].value.default"))
+    parameter_requireds=($(jsonquery "$app_description" "parameters.[].value.required"))
+    parameter_visibles=($(jsonquery "$app_description" "parameters.[].value.visible"))
+    parameter_types=($(jsonquery "$app_description" "parameters.[].value.type"))
+    parameter_min_cardinality=($(jsonquery "${app_description}" "parameters.[].semantics.minCardinality"))
+    parameter_max_cardinality=($(jsonquery "${app_description}" "parameters.[].semantics.maxCardinality"))
     #parameter_enum_values=(`jsonquery "${app_description}" "parameters.[].value.enum_values"`)
     parameter_count=${#parameter_ids[@]}
 
@@ -315,7 +312,7 @@ main() {
     for i in "${parameter_ids[@]}"; do
 
       # figure out fencepost comma problem
-      if [[ "$parameter_count" -eq "$[n+1]" ]]; then
+      if [[ "$parameter_count" -eq "$((n + 1))" ]]; then
         trailingcomma=''
       else
         trailingcomma=','
@@ -325,12 +322,11 @@ main() {
         if [[ "${parameter_requireds[$n]}" == "rue" ]] || [[ "${parameter_requireds[$n]}" == "true" ]] || [[ "$allfields" == 1 ]]; then
           if [[ "${parameter_defaults[$n]}" == "null" ]]; then
 
-
             # strip the array of objects to a list of strings
             tmpEnums=''
             if [[ "${parameter_types[$n]}" == 'enumeration' ]]; then
               tmpEnums=$(jsonquery "${app_description}" "parameters.$n.value.enum_values")
-              tmpEnums=( $(echo "$tmpEnums" | sed 's/:\([a-zA-Z0-9 \-_]*\)}/}/g' | sed 's/\]//g' | sed 's/\[//g' | sed 's/}/"/g' | sed 's/{/"/g' | sed 's/,/ /g' ) )
+              tmpEnums=($(echo "$tmpEnums" | sed 's/:\([a-zA-Z0-9 \-_]*\)}/}/g' | sed 's/\]//g' | sed 's/\[//g' | sed 's/}/"/g' | sed 's/{/"/g' | sed 's/,/ /g'))
             fi
 
             tmp_min_cardinality="${parameter_min_cardinality[$n]}"
@@ -345,7 +341,6 @@ main() {
 
             tmpDefaults=($(generateDefaults "${parameter_types[$n]}" $tmp_min_cardinality $tmp_max_cardinality "${tmpEnums[@]}"))
 
-
             if [[ -n "$tmp_max_cardinality" ]] && [[ "$tmp_max_cardinality" -ne 1 ]] && [[ "${parameter_types[$n]}" != "bool" ]] && [[ "${parameter_types[$n]}" != "flag" ]]; then
               tmpDefaultsCount=${#tmpDefaults[@]}
 
@@ -354,17 +349,17 @@ main() {
               zz=0
               for z in "${tmpDefaults[@]}"; do
                 tc=','
-                if [[ "$tmpDefaultsCount" -eq "$[zz+1]" ]]; then
+                if [[ "$tmpDefaultsCount" -eq "$((zz + 1))" ]]; then
                   tc=''
                 fi
-                if [[ "${parameter_types[$n]}" == "string" ]];then
+                if [[ "${parameter_types[$n]}" == "string" ]]; then
                   parameters=$(printf "%s\n      \"%s\"%s" "$parameters" "$z" "$tc")
                 elif [[ "${parameter_types[$n]}" == "enumeration" ]]; then
                   parameters=$(printf "%s\n      %s%s" "$parameters" "$z" "$tc")
                 else
                   parameters=$(printf "%s\n      %s%s" "$parameters" "$z" "$tc")
                 fi
-                zz=$[zz+1]
+                zz=$((zz + 1))
               done
 
               parameters=$(printf "%s\n    ]%s" "$parameters" "$trailingcomma")
@@ -402,9 +397,9 @@ main() {
             if [[ -n "${parameter_max_cardinality[$n]}" ]] && [[ "${parameter_max_cardinality[$n]}" -ne 1 ]]; then
               tmpEnums=''
               if [[ -n "${parameter_enum_values[$n]}" ]]; then
-                tmpDefaults=( $(echo ${parameter_enum_values[$n]} | sed 's/:\([a-zA-Z0-9 \-_]*\)}/}/g' | sed 's/\]//g' | sed 's/\[//g' | sed 's/}/"/g' | sed 's/{/"/g' | sed 's/,/ /g' ) )
+                tmpDefaults=($(echo ${parameter_enum_values[$n]} | sed 's/:\([a-zA-Z0-9 \-_]*\)}/}/g' | sed 's/\]//g' | sed 's/\[//g' | sed 's/}/"/g' | sed 's/{/"/g' | sed 's/,/ /g'))
               else
-                tmpDefaults=( $(echo ${parameter_defaults[$n]} | sed 's/\[//g' | sed 's/\]//g' | sed 's/,/ /g') )
+                tmpDefaults=($(echo ${parameter_defaults[$n]} | sed 's/\[//g' | sed 's/\]//g' | sed 's/,/ /g'))
               fi
               tmpDefaultsCount=${#tmpDefaults[@]}
 
@@ -413,7 +408,7 @@ main() {
               zz=0
               for z in "${tmpDefaults[@]}"; do
                 tc=','
-                if [[ "$tmpDefaultsCount" -eq "$[zz+1]" ]]; then
+                if [[ "$tmpDefaultsCount" -eq "$((zz + 1))" ]]; then
                   tc=''
                 fi
                 if [[ "${parameter_types[$n]}" == "string" ]]; then
@@ -424,7 +419,7 @@ main() {
                 else
                   parameters=$(printf "%s\n      %s%s" "$parameters" "$z" "$tc")
                 fi
-                zz=$[zz+1]
+                zz=$((zz + 1))
               done
 
               parameters=$(printf "%s\n    ]%s" "$parameters" "$trailingcomma")
@@ -444,7 +439,7 @@ main() {
         fi
       fi
 
-      n=$[n+1]
+      n=$((n + 1))
 
     done
 
@@ -455,9 +450,9 @@ main() {
       if ((verbose)); then
         [ "$piped" -eq 0 ] && log "Fetching your profile description..."
       fi
-      profiles_description=$(profiles-list $debug_flag -v me 2>/dev/null)
+      profiles_description=$(${DIR}/profiles-list $debug_flag -v me 2>/dev/null)
       if [[ -z "$profiles_description" ]]; then
-	       EMPTY_PROFILE=1
+        EMPTY_PROFILE=1
       else
         user_email=$(jsonquery "$profiles_description" "email")
       fi
@@ -504,7 +499,7 @@ main() {
   fi
 }
 
-function generateDefaults {
+function generateDefaults() {
 
   default_values=''
   tmp_val=''
@@ -512,14 +507,14 @@ function generateDefaults {
   asdfasdfasd="$1 $2 $3 $4"
   # $1 target value type
   value_type=$1
-  shift;
+  shift
 
   # $2 minCardinality
   min_card=$1
   if [[ -z "$min_card" ]]; then
     min_card=1
   fi
-  shift;
+  shift
 
   # $3 maxCardinality
   if [[ -z "$1" ]]; then
@@ -529,7 +524,7 @@ function generateDefaults {
   else
     max_card=$1
   fi
-  shift;
+  shift
 
   # $4 enumValues
   if [[ -z "$1" ]]; then
@@ -556,17 +551,17 @@ function generateDefaults {
     for i in $value_range; do
       tmp_val=''
       if [[ "$value_type" == "integer" ]]; then
-        tmp_val=$(( ( RANDOM % 100000 )  + 1 ))
+        tmp_val=$(((RANDOM % 100000) + 1))
       elif [[ "$value_type" == "decimal" ]]; then
-        tmp_int=$(( ( RANDOM % 10000 )  + 1 ))
-        tmp_dec=$(( ( RANDOM % 1000 )  + 1 ))
+        tmp_int=$(((RANDOM % 10000) + 1))
+        tmp_dec=$(((RANDOM % 1000) + 1))
         tmp_val=$tmp_int.$tmp_dec
       elif [[ "$value_type" == "number" ]]; then
-        tmp_val=$(( ( RANDOM % 100000 )  + 1 ))
+        tmp_val=$(((RANDOM % 100000) + 1))
       elif [[ "$value_type" == "input" ]]; then
-        seed=$(( ( RANDOM % 2 ) + 1 ))
+        seed=$(((RANDOM % 2) + 1))
         # get a random agave url for the user
-        tmp_fname=`head -c 10 /dev/urandom | base64`
+        tmp_fname=$(head -c 10 /dev/urandom | base64)
         tmp_fname=${tmp_fname%\/}
         if [[ "$seed" -eq 1 ]]; then
           # get a random meme url from imgur
@@ -577,10 +572,10 @@ function generateDefaults {
           tmp_val="${username}/inputs/${tmp_fname:0:12}.dat"
         fi
       elif [[ "$value_type" == "enumeration" ]]; then
-        enumindex=$(( ( RANDOM % $enum_count ) ))
+        enumindex=$(((RANDOM % $enum_count)))
         tmp_val=${enum_values[$enumindex]}
       else
-        tmp_val=`head -c 10 /dev/urandom | base64`
+        tmp_val=$(head -c 10 /dev/urandom | base64)
         tmp_val=${tmp_val%\/}
         tmp_val="${tmp_val:0:7}"
       fi
@@ -607,31 +602,56 @@ function generateDefaults {
 # Parse command line options
 source "$DIR/options.sh"
 
-
 # Main loop {{{
 
 # Print help if no arguments were passed.
 #[[ $# -eq 0 ]] && set -- "--help"
 
 # Read the options and set stuff
-while [[ $1 = -?* ]]; do
+while [[ $1 == -?* ]]; do
   case $1 in
-    -h|--help) usage >&2; safe_exit ;;
-    --version) version; copyright; disclaimer; safe_exit ;;
-    -z|--access_token) shift; access_token=$1 ;;
-    -N|--name) shift; name=$1 ;;
-    -E|--empty) shift; empty=$1 ;;
-    -A|--allfields) allfields=1 ;;
-    -C|--cache) cache=1 ;;
-    -H|--hosturl) shift; hosturl=$1;;
-  	-d|--development) development=1 ;;
-    -v|--verbose) verbose=1 ;;
-    -V|--veryverbose) veryverbose=1; verbose=1 ;;
-    -q|--quiet) quiet=1 ;;
-    -i|--interactive) interactive=1 ;;
-    -f|--force) force=1 ;;
-    --endopts) shift; break ;;
-    *) die "invalid option: $1" ;;
+  -h | --help)
+    usage >&2
+    safe_exit
+    ;;
+  --version)
+    version
+    copyright
+    disclaimer
+    safe_exit
+    ;;
+  -z | --access_token)
+    shift
+    access_token=$1
+    ;;
+  -N | --name)
+    shift
+    name=$1
+    ;;
+  -E | --empty)
+    shift
+    empty=$1
+    ;;
+  -A | --allfields) allfields=1 ;;
+  -C | --cache) cache=1 ;;
+  -H | --hosturl)
+    shift
+    hosturl=$1
+    ;;
+  -d | --development) development=1 ;;
+  -v | --verbose) verbose=1 ;;
+  -V | --veryverbose)
+    veryverbose=1
+    verbose=1
+    ;;
+  -q | --quiet) quiet=1 ;;
+  -i | --interactive) interactive=1 ;;
+  -f | --force) force=1 ;;
+  --endopts)
+    shift
+    break
+    ;;
+  *) die "invalid option: $1" ;;
   esac
   shift
 done
