catching up to main trunk

diff --git a/bin/uuid-lookup b/bin/uuid-lookup
--- a/bin/uuid-lookup
+++ b/bin/uuid-lookup
@@ -18,9 +18,11 @@ source "$DIR/common.sh"
 # to be named exactly as the longname option definition in usage().
 interactive_opts=()
 
+expand=false
+
 # Print usage
 usage() {
-  echo -n "$(basename $0) [OPTION]...
+  echo -n "$(basename $0) [OPTION]... UUID [UUID]
 
 Lookup the resource for a given UUID when the resource type is not known.
 
@@ -28,6 +30,7 @@ Lookup the resource for a given UUID when the resource type is not known.
   -H, --hosturl        URL of the service
   -d, --development    Run in dev mode using default dev server
   -e, --expand  	   Expand the response with the full resource representation
+      --filter         Comma separated list of fields to return in the response
   -f, --force          Skip all user interaction
   -i, --interactive    Prompt for values
   -q, --quiet          Quiet (no output)
@@ -51,65 +54,53 @@ main() {
 	#set -x
 
 	baseuuidurl=${hosturl%/}
+
 	if [ -z "$args" ]; then
 		err "Please specify one or more valid uuid to resolve"
+
+	# only one uuid was provided. return an object
+	elif [[ ${#args[@]} -eq 1 ]]; then
+
+		hosturl="$baseuuidurl/$args"
+
+		cmd="curl -sk -H \"${authheader}\" '${hosturl}?expand=$expand&pretty=true$(pagination)'"
+
+		if ((veryverbose)); then
+			[ "$piped" -eq 0 ] && log "Calling $cmd"
+		fi
+
+		response=`curl -sk -H "${authheader}" "${hosturl}?expand=$expand&pretty=true$(pagination)"`
+
+		# resolve the uuid. if successful, parse it
+		if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+			result=$(format_api_json "$response")
+			success "$result"
+		else
+			errorresponse=$(jsonquery "$response" "message")
+			err "$errorresponse"
+		fi
+
+	# multiple uuid were provided. return an array
 	else
+		# convert them to a comma separated list
+		uuids=$(echo "${args}" | sed -e 's/ /,/g')
 
-		for uuid in "${args[@]}"
-		do
-			hosturl="$baseuuidurl/$uuid"
+		cmd="curl -sk -H \"${authheader}\" '${hosturl}?uuids=$uuids&expand=$expand&pretty=true$(pagination)'"
 
-			cmd="curl -sk -H \"${authheader}\" '${hosturl}?pretty=true$(pagination)'"
+		if ((veryverbose)); then
+			[ "$piped" -eq 0 ] && log "Calling $cmd"
+		fi
 
-			if ((veryverbose)); then
-				[ "$piped" -eq 0 ] && log "Calling $cmd"
-			fi
+		response=`curl -sk -H "${authheader}" "${hosturl}?uuids=$uuids&expand=$expand&pretty=true$(pagination)"`
 
-			response=`curl -sk -H "${authheader}" "${hosturl}?pretty=true$(pagination)"`
-
-			# resolve the uuid. if successful, parse it
-			if [[ $(jsonquery "$response" "status") = 'success' ]]; then
-
-				if ((veryverbose)); then
-					echo "$response"
-				fi
-
-				# if the user wants the uuid expanded into a resource representation,
-				# we'll use the returned URL and fetch the resource.
-				if ((expand)); then
-
-					resourceurl=$(jsonquery "$response" "result._links.self.href")
-
-					if [[ -n "$resourceurl" ]]; then
-
-						hosturl="$resourceurl"
-
-						subcmd="curl -sk -H \"${authheader}\" '${hosturl}?pretty=true$(pagination)'"
-
-						if ((veryverbose)); then
-							[ "$piped" -eq 0 ] && log "Expanding resource at $hosturl.\nCalling $subcmd"
-						fi
-
-						# The expanded resource becomes the response to this command
-						response=`curl -sk -H "${authheader}" "${hosturl}?pretty=true$(pagination)"`
-					fi
-				fi
-
-				# standard success handling if successful.
-				if [[ $(jsonquery "$response" "status") = 'success' ]]; then
-					result=$(format_api_json "$response")
-					success "$result"
-				# in the event expansion was requested and it failed,
-				else
-					errorresponse=$(jsonquery "$response" "message")
-					err "$errorresponse"
-				fi
-
-			else
-				errorresponse=$(jsonquery "$response" "message")
-				err "$errorresponse"
-			fi
-		done
+		# resolve the uuid. if successful, parse it
+		if [[ $(jsonquery "$response" "status") = 'success' ]]; then
+			result=$(format_api_json "$response")
+			success "$result"
+		else
+			errorresponse=$(jsonquery "$response" "message")
+			err "$errorresponse"
+		fi
 	fi
 }
 
@@ -117,13 +108,29 @@ format_api_json() {
 
 	if ((veryverbose)); then
 		echo "$1"
-	elif [[ $verbose -eq 1 ]] || ((expand)); then
+	elif (( $verbose )) || ((expand)); then
 		result=$(jsonquery "$1" "result" 1)
 		json_prettyify "${result}"
 	else
-		resource_type=$(jsonquery "$1" "result.type")
-		resource_url=$(jsonquery "$1" "result._links.self.href")
-		echo "$resource_type $resource_url"
+		if [[ ${#args[@]} -eq 1 ]]; then
+			resource_type=$(jsonquery "$1" "result.type")
+			resource_url=$(jsonquery "$1" "result._links.self.href")
+			echo "$resource_type $resource_url"
+		else
+			resource_types=( $(jsonquery "$1" "result.[].id") )
+			resource_urls=( $(jsonquery "$1" "result.[]._links.self.href") )
+
+			n=0
+			for i in "${args[@]}"
+			do
+				resources[$n]="$i ${resource_types[$n]} ${resource_urls[$n]}"
+				n=$[n+1]
+			done
+
+			for i in "${resources[@]}"; do
+				echo "$i"
+			done
+		fi
 	fi
 }
 
@@ -148,8 +155,9 @@ while [[ $1 = -?* ]]; do
   case $1 in
     -h|--help) usage >&2; safe_exit ;;
     --version) version; copyright; disclaimer; safe_exit ;;
-    -e|--expand) expand=1 ;;
-    -H|--hosturl) shift; hosturl=$1;;
+    -e|--expand) expand=true ;;
+    --filter) shift; responsefilter=$1 ;;
+	-H|--hosturl) shift; hosturl=$1;;
   	-d|--development) development=1 ;;
     -v|--verbose) verbose=1 ;;
     -V|--veryverbose) veryverbose=1; verbose=1 ;;
